version: "3.5"

services:
  nginx:
    build: .
    network_mode: host
    ports:
      - 80:80

  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    image: ictalk:latest
    container_name: ictalk-docker
    ports:
      - 3001:3001
